version: '3.8'
services:
  main:
    image: smaranm/main_image
    container_name: main_container
    networks:
      static_net:
        ipv4_address: 192.168.1.2
    depends_on:
      - courses
      - staff
      - gallery
      - contact_us

  courses:
    image: smaranm/courses_image
    container_name: courses_container
    networks:
      static_net:
        ipv4_address: 192.168.1.3

  staff:
    image: smaranm/staff_image
    container_name: staff_container
    networks:
      static_net:
        ipv4_address: 192.168.1.4

  gallery:
    image: smaranm/gallery_image
    container_name: gallery_container
    networks:
      static_net:
        ipv4_address: 192.168.1.5

  contact_us:
    image: smaranm/contact-us_image
    container_name: contactus_container
    networks:
      static_net:
        ipv4_address: 192.168.1.6

networks:
  static_net:
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24

